version: "3.9"
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    environment:
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - "9200"
  api:
    build: ./api/faers
    environment:
      - ES_HOST=es:9200
    depends_on:
      - es
    ports:
      - 8000:8000
  pipeline:
    build: .
    environment:
      - ES_HOST=es:9200
    depends_on:
      - es
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
  test:
    profiles: ["test"]
    build: .
    command: ["./scripts/run_unit_tests.sh"]
    volumes:
      - ./:/opt/openfda
    environment:
      - ES_HOST=es:9200
    depends_on:
      - es
